/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:91937b68-f8ec-4849-9582-1c3688b98e89",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_yk2Emks5G",
    "aws_user_pools_web_client_id": "7ars7rhvr3mapeska9luuv6kem",
    "oauth": {}
};


export default awsmobile;
